### ISSUE TITLE
Product Image bug

### ISSUE THREAD

**Issue by TBF-Will** [addonify/addonify-floating-cart#275] opened 2023-12-13 15:59 UTC
Hi! Just wanted to say this is a great plugin.

I have found a bug which means the product images are being stretched in the cart. This only happens when I add the first product, If I navigate away from the page and add another product the product image is fixed. Is there some CSS that I can add to fix the issue?

I've attached a link to a screenshot here: https://ibb.co/CJyMP2D this shows the stretched image and this shows the normal image after I add another product: https://ibb.co/xjMJhFf

Thanks for your help :)
Will

**Comment by h1dd3nsn1p3r** [comment] 2023-12-13 16:13
Hi @TBF-Will Can you please share your website URL?

**Comment by TBF-Will** [comment] 2023-12-13 16:26
Sure :) here you go: https://farmshopdev.theblackfarmer.com/

**Comment by h1dd3nsn1p3r** [comment] 2023-12-14 06:35
Sorry, I was not able to reproduce the issue you have described. Can you please share a screencast video?

**Comment by h1dd3nsn1p3r** [comment] 2023-12-28 05:06
Closing this issue.

**Closed as completed by h1dd3nsn1p3r** 2023-12-28 05:06 UTC
